### ISSUE TITLE
Venue page maps not working

### ISSUE THREAD

**Issue by mousedownmike** [TXLF/2024website#5]
The venue page has a Google map that appears to be using a developer key or possibly no key at all. No venues are visible. 

![image](https://github.com/TXLF/2024website/assets/47116171/6cafadf1-4c24-43a2-850b-9e03d74df9b7)

**Comment by mousedownmike** [comment]
https://2024.texaslinuxfest.org/venue_hotels/

Using Firefox, Ubuntu 22.04

**Comment by AdamBark** [comment]
Thanks. The map is gone from that page and the home page uses Open Street Map now.
